### ISSUE TITLE
circleCI doesn't like es6

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-api#100]
snipped taken from circleCI logs. @Dignifiedquire @VictorBjelkholm thoughts? :) 

```bash
> gulp test

[16:20:06] Using gulpfile ~/js-ipfs-api/gulpfile.js
[16:20:06] Starting 'test'...
[16:20:06] Starting 'test:node'...
[16:20:06] Starting 'daemons:start'...

/home/ubuntu/js-ipfs-api/node_modules/ipfsd-ctl/node_modules/ipfs-api/src/request-api.js:3
const request = require('request')
^^^^^
[16:20:07] 'daemons:start' errored after 233 ms
[16:20:07] SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by Dignifiedquire** [comment]
outdted node version, probably need to add a config file

**Comment by harlantwood** [comment]
circle.yml might look like this:

```
test:
  override:
    - nvm install stable && nvm alias default stable
    - npm test
```

**Comment by harlantwood** [comment]
fixed in #106

**Comment by diasdavid** [comment]
Sweeet! Thank you @harlantwood :D

**Comment by harlantwood** [comment]
Sure!
