### ISSUE TITLE
Commit hook unexpected and not working on my build

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/js-ipfs-api#157]
I'm trying to fix #155 and I came upon this error when trying to commit. Any ideas? 

```
🐕  git commit
/Users/richard/src/js-ipfs-api/gulpfile.js:8
gulp.task('default', done => {
                          ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:427:25)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at Liftoff.handleArguments (/Users/richard/src/js-ipfs-api/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/richard/src/js-ipfs-api/node_modules/liftoff/index.js:192:16)
    at module.exports (/Users/richard/src/js-ipfs-api/node_modules/flagged-respawn/index.js:17:3)
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `lint`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 
```

**Comment by Dignifiedquire** [comment]
sounds like you have an outdated version of node, make sure you have >= 4.0

**Comment by RichardLitt** [comment]
D'oh!
