### ISSUE TITLE
Could not parse row {... when using ipfs.add( new Buffer( "test"), function(){ console.log(arguments) }

### ISSUE THREAD

**Issue by hems** [ipfs/js-ipfs-api#197]
for some weird reason i'm getting that ````Could not parse row {...```` error when trying to use the "add" method with a provided buffer.

````
ipfs.add( new Buffer("something"), -> console.log arguments )
````

the whole log is here:
````
offee> ipfs.add( new Buffer("something"), -> console.log arguments )
undefined
coffee> Error: Could not parse row {...
  at DestroyableTransform.parseRow [as mapper] (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/index.js:18:28)
  at DestroyableTransform.transform [as _transform] (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/split2/index.js:27:21)
  at DestroyableTransform.Transform._read (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at IncomingMessage.ondata (_stream_readable.js:528:20)
  at emitOne (events.js:77:13)
  at IncomingMessage.emit (events.js:169:7)
  at IncomingMessage.Readable.read (_stream_readable.js:360:10)
  at flow (_stream_readable.js:743:26)
  at resume_ (_stream_readable.js:723:3)
  at doNTCallback2 (node.js:452:9)
  at process._tickDomainCallback (node.js:407:17)

coffee> Error: Could not parse row   "Name": "QmX7epzCn2jD8nPUDiehmZDQs69HxKYcmMGjd3r...
  at DestroyableTransform.parseRow [as mapper] (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/index.js:18:28)
  at DestroyableTransform.transform [as _transform] (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/split2/index.js:33:21)
  at DestroyableTransform.Transform._read (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at IncomingMessage.ondata (_stream_readable.js:528:20)
  at emitOne (events.js:77:13)
  at IncomingMessage.emit (events.js:169:7)
  at IncomingMessage.Readable.read (_stream_readable.js:360:10)
  at flow (_stream_readable.js:743:26)
  at resume_ (_stream_readable.js:723:3)
  at doNTCallback2 (node.js:452:9)
  at process._tickDomainCallback (node.js:407:17)

coffee> Error: Could not parse row   "Hash": "QmX7epzCn2jD8nPUDiehmZDQs69HxKYcmMGjd3r...
  at DestroyableTransform.parseRow [as mapper] (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/index.js:18:28)
  at DestroyableTransform.transform [as _transform] (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/split2/index.js:33:21)
  at DestroyableTransform.Transform._read (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at IncomingMessage.ondata (_stream_readable.js:528:20)
  at emitOne (events.js:77:13)
  at IncomingMessage.emit (events.js:169:7)
  at IncomingMessage.Readable.read (_stream_readable.js:360:10)
  at flow (_stream_readable.js:743:26)
  at resume_ (_stream_readable.js:723:3)
  at doNTCallback2 (node.js:452:9)
  at process._tickDomainCallback (node.js:407:17)

coffee> Error: Could not parse row }...
  at DestroyableTransform.parseRow [as mapper] (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/index.js:18:28)
  at DestroyableTransform.transform [as _transform] (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/split2/index.js:33:21)
  at DestroyableTransform.Transform._read (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Volumes/backpack/git/verb/verbatm/tests/ipfs/node_modules/ipfs-api/node_modules/ndjson/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at IncomingMessage.ondata (_stream_readable.js:528:20)
  at emitOne (events.js:77:13)
  at IncomingMessage.emit (events.js:169:7)
  at IncomingMessage.Readable.read (_stream_readable.js:360:10)
  at flow (_stream_readable.js:743:26)
  at resume_ (_stream_readable.js:723:3)
  at doNTCallback2 (node.js:452:9)
  at process._tickDomainCallback (node.js:407:17)

**Comment by dignifiedquire** [comment]
what version of ipfsare you using?

**Comment by diasdavid** [comment]
@hems make sure you are using latest IPFS (0.3.11) with js-ipfs-api

**Comment by hems** [comment]
so i  installed using brew and the version 0.3.9 came.

after doing some updates, i manage to get 0.3.11 and using latest iojs it worked like a charm.

thanks guys.

**Comment by mhhf** [comment]
I still have a problem with this using ipfs-api 2.13.1 and ipfs on 0.3.11 on OS X 10.10.5 with node 5.4.1
