### ISSUE TITLE
README should mention node version requirement

### ISSUE THREAD

**Issue by moshisushi** [ipfs/js-ipfs-api#260]
I tried using ipfs-api on my debian 8.3 "jessie" server, using the node/npm packages available through api:

$ /usr/bin/nodejs --version
v0.10.29
$ /usr/bin/npm --version
1.4.21
$ /usr/bin/npm install --save ipfs-api

... installs deps ...

$ cat test.js
var ipfsApi = require('ipfs-api');
$ /usr/bin/nodejs test

/home/holodisc/test/node_modules/ipfs-api/node_modules/wreck/lib/index.js:5
const Events = require('events');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/holodisc/test/node_modules/ipfs-api/lib/request-api.js:13:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

However, if i install node v4.4.3 everything works OK!

I don't know if this is expected, but in any case I believe this requirement should be documented in the README.

**Comment by diasdavid** [comment]
@moshisushi we've added a `engine` clause to our package.json https://github.com/ipfs/js-ipfs-api/blob/master/package.json#L18-L20, sorry it didn't get enforced on your env and broke things for you.

We've been supporting LTS versions of Node.js starting from Node.js 4

**Comment by diasdavid** [comment]
Would you like to submit a PR? :)

**Comment by moshisushi** [comment]
@diasdavid Sure I'll fix one later today :)

**Comment by diasdavid** [comment]
thank you for the PR @moshisushi :)
