### ISSUE TITLE
Browser tests are broken

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-api#382]
Some time ago we disabled browser tests on CI, and it seems this has bitten us now. Currently the browser tests are failing, and it seems they have been for some time.

**Comment by dignifiedquire** [comment]
```
 npm run test:browser

> ipfs-api@8.0.4 test:browser /Users/dignifiedquire/opensource/ipfs/js-ipfs-api
> node --max_old_space_size=4096 node_modules/.bin/gulp test:browser

[10:32:13] Using gulpfile ~/opensource/ipfs/js-ipfs-api/gulpfile.js
[10:32:13] Starting 'test:browser'...
[10:32:13] Starting 'daemons:start'...
[10:32:13] Starting 'factory:start'...
[10:32:13] Finished 'factory:start' after 121 ms
  ipfs init done - (bootstrap and mdns off) - a
  ipfs init done - (bootstrap and mdns off) - b
  ipfs init done - (bootstrap and mdns off) - c
[10:32:15] Finished 'daemons:start' after 1.97 s
[10:32:15] Starting 'test:browser:before'...
[10:32:15] Finished 'test:browser:before' after 17 μs
[10:32:15] Starting 'karma'...


15 09 2016 10:33:51.016:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
15 09 2016 10:33:51.022:INFO [launcher]: Launching browsers Chrome, PhantomJS with concurrency 1
15 09 2016 10:33:51.037:INFO [launcher]: Starting browser Chrome
15 09 2016 10:33:54.460:INFO [Chrome 53.0.2785 (Mac OS X 10.11.6)]: Connected on socket /#wTU2xKI1BlLx3lSrAAAA with id 79027754
15 09 2016 10:34:28.767:WARN [reporter]: SourceMap position not found for trace: undefined
15 09 2016 10:34:28.769:WARN [reporter]: SourceMap position not found for trace: undefined
  1) "before all" hook
  2) "after all" hook
15 09 2016 10:34:29.120:INFO [launcher]: Starting browser PhantomJS
15 09 2016 10:34:30.183:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#5BZgiIjQ2hUBy1DOAAAB with id 64335308
15 09 2016 10:34:41.416:WARN [reporter]: SourceMap position not found for trace: undefined
15 09 2016 10:34:41.419:WARN [reporter]: SourceMap position not found for trace: undefined
15 09 2016 10:34:41.420:WARN [reporter]: SourceMap position not found for trace: undefined
  3) "before all" hook
  4) "after all" hook

  0 passing (2m)
  4 failing

  1) "before all" hook:
     ReferenceError: Invalid left-hand side in assignment
    at webpack:///~/node-forge/js/forge.js?de7f*****************:50:0 <- test/browser.js:36422:1
    at Object.<anonymous> (webpack:///~/node-forge/js/forge.js?de7f*****************:92:1 <- test/browser.js:36464:3)
    at __webpack_require__ (webpack:/webpack/bootstrap%20f599c3683fdb01263328?0884*****************:19:0 <- test/browser.js:21:30)
    at Object.<anonymous> (webpack:///~/libp2p-crypto/lib/keys/rsa.js?8677*****************:7:0 <- test/browser.js:65431:13)
    at Object.<anonymous> (test/browser.js:65596:30)
    at __webpack_require__ (webpack:/webpack/bootstrap%20f599c3683fdb01263328?0884*****************:19:0 <- test/browser.js:21:30)
    at Object.<anonymous> (webpack:///~/libp2p-crypto/lib/keys/index.js?db8b*****************:4:0 <- test/browser.js:65417:8)
    at __webpack_require__ (webpack:/webpack/bootstrap%20f599c3683fdb01263328?0884*****************:19:0 <- test/browser.js:21:30)
    at Object.<anonymous> (webpack:///~/libp2p-crypto/lib/index.js?ce23*****************:9:0 <- test/browser.js:65233:27)
    at Object.<anonymous> (test/browser.js:65303:30)



  2) "after all" hook:
     TypeError: Cannot read property 'swarm' of undefined
    at disconnectNodes (webpack:///test/setup/setup-ipfs-api-clients.js:52:22 <- test/browser.js:82959:22)
    at Context.<anonymous> (webpack:///test/setup/setup-ipfs-api-clients.js:76:2 <- test/browser.js:82983:3)



  3) "before all" hook:
     Left side of assignment is not a reference.
webpack:///~/node-forge/js/forge.js?de7f*****************:50:0 <- test/browser.js:36422:25
webpack:///~/node-forge/js/forge.js?de7f*****************:92:1 <- test/browser.js:36464:3
__webpack_require__@webpack:/webpack/bootstrap%20f599c3683fdb01263328?0884*****************:19:0 <- test/browser.js:21:34
webpack:///~/libp2p-crypto/lib/keys/rsa.js?8677*****************:7:0 <- test/browser.js:65431:32
test/browser.js:65596:34
__webpack_require__@webpack:/webpack/bootstrap%20f599c3683fdb01263328?0884*****************:19:0 <- test/browser.js:21:34
webpack:///~/libp2p-crypto/lib/keys/index.js?db8b*****************:4:0 <- test/browser.js:65417:27
__webpack_require__@webpack:/webpack/bootstrap%20f599c3683fdb01263328?0884*****************:19:0 <- test/browser.js:21:34
webpack:///~/libp2p-crypto/lib/index.js?ce23*****************:9:0 <- test/browser.js:65233:46
test/browser.js:65303:34
__webpack_require__@webpack:/webpack/bootstrap%20f599c3683fdb01263328?0884*****************:19:0 <- test/browser.js:21:34
webpack:///~/peer-id/lib/index.js?3695*****************:12:0 <- test/browser.js:46196:33
test/browser.js:46365:34
__webpack_require__@webpack:/webpack/bootstrap%20f599c3683fdb01263328?0884*****************:19:0 <- test/browser.js:21:34
webpack:///src/api/swarm.js?6d3e*****************:5:23 <- test/browser.js:52813:33
__webpack_require__@webpack:/webpack/bootstrap%20f599c3683fdb01263328?0884*****************:19:0 <- test/browser.js:21:34
requireCommands@webpack:///src/load-commands.js?31f0*****************:27:19 <- test/browser.js:53314:31
loadCommands@webpack:///src/load-commands.js?31f0*****************:57:16 <- test/browser.js:53344:30
IpfsAPI@webpack:///src/index.js?9552*****************:39:28 <- test/browser.js:50887:26
webpack:///test/setup/setup-ipfs-api-clients.js:69:37 <- test/browser.js:82976:37
forEach@[native code]
webpack:///test/setup/setup-ipfs-api-clients.js:68:32 <- test/browser.js:82975:32



  4) "after all" hook:
     undefined is not an object (evaluating 'global.apiClients.a.swarm')
disconnectNodes@webpack:///test/setup/setup-ipfs-api-clients.js:52:22 <- test/browser.js:82959:22
webpack:///test/setup/setup-ipfs-api-clients.js:76:18 <- test/browser.js:82983:18





[10:34:41] 'karma' errored after 2.43 min
[10:34:41] Error: Some tests are failing
    at formatError (/Users/dignifiedquire/opensource/ipfs/js-ipfs-api/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/dignifiedquire/opensource/ipfs/js-ipfs-api/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/dignifiedquire/opensource/ipfs/js-ipfs-api/node_modules/orchestrator/index.js:264:8)
    at /Users/dignifiedquire/opensource/ipfs/js-ipfs-api/node_modules/orchestrator/index.js:275:23
    at finish (/Users/dignifiedquire/opensource/ipfs/js-ipfs-api/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/dignifiedquire/opensource/ipfs/js-ipfs-api/node_modules/orchestrator/lib/runTask.js:29:3)
    at Server (/Users/dignifiedquire/opensource/ipfs/js-ipfs-api/node_modules/aegir/tasks/test/browser.js:16:9)
    at removeAllListeners (/Users/dignifiedquire/opensource/ipfs/js-ipfs-api/node_modules/karma/lib/server.js:379:7)
    at Server.<anonymous> (/Users/dignifiedquire/opensource/ipfs/js-ipfs-api/node_modules/karma/lib/server.js:390:9)
    at Server.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitCloseNT (net.js:1549:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
