### ISSUE TITLE
Error: Cannot find module 'readable-stream'

### ISSUE THREAD

**Issue by SCBuergel** [ipfs/js-ipfs-api#394]
I am running the latest x64 build of IPFS on the Ethereum Studio (live.ether.camp):
```
root@fbba31d85e3b:~/workspace/hello# ipfs --version
ipfs version 0.4.3
```
I have a local IPFS node running which can successfully `add` and `cat` content. When using the IPFS JS API (my `package.json` tells me `"ipfs-api": "^9.0.0",`) I am running into the following error when I do `var ipfs = ipfsApi();`:
```
module.js:327
    throw err;
    ^

Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/workspace/hello/node_modules/ipfs-api/lib/tar-stream-to-objects.js:4:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```
The error persists disregarding if my IPFS daemon is running or not.

Some more info:
```
root@fbba31d85e3b:~/workspace/hello# node --version
v4.5.0
root@fbba31d85e3b:~/workspace/hello# npm --version
2.15.9
root@fbba31d85e3b:~/workspace/hello# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
```

**Comment by diasdavid** [comment]
@SCBuergel try with the latest version of npm, try `npm i npm -g` version to get npm 3. Let me know if you find any other trouble

**Comment by SCBuergel** [comment]
Thank you, installing the latest `npm` and `nodejs-legacy` on Ethereum Studio fixed this. Seems this was and issue on their end with outdated packages and not yours.

**Comment by redcherry999** [comment]
Hello sir ,

i'm getting same errror as 

`module.js:327
    throw err;
    ^

Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/root/aws_nodejs/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/store.js:2:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
`
 i have run the command "npm i npm -g" to get npm 3 but it is giving same error

**Comment by VictorBjelkholm** [comment]
@redcherry999 could you show the full output of running `npm version`? It should output a JSON bit with all the versions.

**Comment by doniaZaela** [comment]
Hi,
I am getting the same error:
![image](https://user-images.githubusercontent.com/34517889/38821356-ad2d4836-4176-11e8-82a7-ab31448c39c1.png)

and when I run "npm i npm -g", I get the following error:

![image](https://user-images.githubusercontent.com/34517889/38821546-2e88789c-4177-11e8-919c-c6c849aced41.png)

Any clues?
