### ISSUE TITLE
Not installable on NPMv2

### ISSUE THREAD

**Issue by bergie** [ipfs/js-ipfs-api#407]
It seems either ipfs-api or one of its dependencies is missing a dependency declaration, and so only works in the NPMv3 flattened tree.

With NPMv2 it fails with:

```
{ [Error: Cannot find module 'multihashes'] code: 'MODULE_NOT_FOUND' }
```

**Comment by jonnor** [comment]
```
npm info using npm@2.14.7
npm info using node@v4.2.1
```

Note that it is not at npm install time it fails, but when requiring `ipfs-api`.

**Comment by jonnor** [comment]
err! { [Error: Cannot find module 'multihashes'] code: 'MODULE_NOT_FOUND' }
err! Error: Cannot find module 'multihashes'
  at Function.Module._resolveFilename (module.js:337:15)
  at Function.Module._load (module.js:287:25)
  at Function.cls_wrapMethod [as _load] (/usr/src/app/node_modules/newrelic/lib/shimmer.js:256:38)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/usr/src/app/node_modules/ipfs-api/lib/api/block.js:8:17)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (/usr/src/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Function.cls_wrapMethod [as _load] (/usr/src/app/node_modules/newrelic/lib/shimmer.js:256:38)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at requireCommands (/usr/src/app/node_modules/ipfs-api/lib/load-commands.js:10:12)
  at loadCommands (/usr/src/app/node_modules/ipfs-api/lib/load-commands.js:57:15)
  at IpfsAPI (/usr/src/app/node_modules/ipfs-api/lib/index.js:40:14)
  at Object.module.exports.init (/usr/src/app/models/cache/ipfs.coffee:12:15)
  at Object.exports.getApp (/usr/src/app/web/app.coffee:36:22)
  at Object.<anonymous> (/usr/src/app/server.js:7:5)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

**Comment by bergie** [comment]
Yup, these modules are required in https://github.com/ipfs/js-ipfs-api/blob/master/src/api/block.js#L6

* multihashes
* cids

...but are not dependend on in `package.json`

**Comment by jonnor** [comment]
And
```
err! Error: Cannot find module 'readable-stream'
...
  at Object.<anonymous> (/usr/src/app/node_modules/ipfs-api/lib/tar-stream-to-objects.js:4:16)
```

**Comment by dignifiedquire** [comment]
This should be fixed on `master` please let us know if you are still running into problems

**Comment by diasdavid** [comment]
npm 3 is a requirement of this module, unfortunately there is no mechanism to notify the user of that during the install process, you can see the minimum engine and npm at the readme of this project

https://github.com/ipfs/js-ipfs-api#ipfs-api

Closing this issue, let us know if you run into problems with npm 3

**Comment by jonnor** [comment]
@diasdavid If you set the versios needed in `engines` key in `package.json`, then `npm install` will warn the user: https://docs.npmjs.com/files/package.json#engines

**Comment by diasdavid** [comment]
oh sweet! I knew about node, but didn't know it would check for npm as well. added on https://github.com/ipfs/js-ipfs-api/commit/505ce8e9a933461ac0417fc200a32c286f670a44
