### ISSUE TITLE
Uncaught exception in electron if daemon is inactive

### ISSUE THREAD

**Issue by pfrazee** [ipfs/js-ipfs-api#443]
If I run any command when the daemon isnt running, regardless of my error handling on the command, I get two alerts for uncaught exceptions:

```
Uncaught Exception:
Error: connect ECONNREFUSED 127.0.0.1:5001
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```

and

```
Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)
```

I looked through the source and didnt see anyway to hook into (and handle) those events. Any thoughts? (Would be great to have them exposed as events that I can respond to.)

**Comment by diasdavid** [comment]
Fixed with https://github.com/ipfs/js-ipfs-api/pull/445 thanks for reporting :)
