### ISSUE TITLE
Run the `js-ipfs-api` tests again in go-ipfs CI

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/js-ipfs-api#486]
We use js-ipfs-api tests in go-ipfs to check if we didn't break those parts of API. Currently the CI is almost always red and it means that we will get used to that and just start ignoring the status as it isn't reliable.

See: http://ci.ipfs.team:8111/viewLog.html?buildId=10087&buildTypeId=GoIpfs_JsIpfsApiTests&tab=buildLog for error message

The test is started with `npm run test:node`.

**Comment by diasdavid** [comment]
That is strange @Kubuxu , o you experience the same in your local machine or just team city?

**Comment by Kubuxu** [comment]
Haven't tested it on local machine but I will give it a try.

**Comment by Kubuxu** [comment]
The tests fail locally for me in many weird places and I don't want to try debugging the node env, if you could try reproducing it in your env it would be great.

It doesn't fail 100% but I think it is more than 50%-70% of failures.

**Comment by diasdavid** [comment]
@Kubuxu Unfortunately I'm not being able to reproduce it. Which Node.js and npm versions are you using?


Totally agree that this is undesirable as you will just start skipping the tests, thank you for reporting.

**Comment by Kubuxu** [comment]
Just had a failure on node with: npm: 3.10.8 and node: 6.9.1

**Comment by Kubuxu** [comment]
npm-debug.log:
```
[11:58:50][Step 4/4] 0 info it worked if it ends with ok
[11:58:50][Step 4/4] 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'test:node' ]
[11:58:50][Step 4/4] 2 info using npm@3.10.8
[11:58:50][Step 4/4] 3 info using node@v6.9.1
[11:58:50][Step 4/4] 4 verbose run-script [ 'pretest:node', 'test:node', 'posttest:node' ]
[11:58:50][Step 4/4] 5 info lifecycle ipfs-api@12.1.0~pretest:node: ipfs-api@12.1.0
[11:58:50][Step 4/4] 6 silly lifecycle ipfs-api@12.1.0~pretest:node: no script for pretest:node, continuing
[11:58:50][Step 4/4] 7 info lifecycle ipfs-api@12.1.0~test:node: ipfs-api@12.1.0
[11:58:50][Step 4/4] 8 verbose lifecycle ipfs-api@12.1.0~test:node: unsafe-perm in lifecycle true
[11:58:50][Step 4/4] 9 verbose lifecycle ipfs-api@12.1.0~test:node: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/teamcity/work/3144e2a06f62fd48/js-ipfs-api/node_modules/.bin:/teamcity/work/3144e2a06f62fd48/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[11:58:50][Step 4/4] 10 verbose lifecycle ipfs-api@12.1.0~test:node: CWD: /teamcity/work/3144e2a06f62fd48/js-ipfs-api
[11:58:50][Step 4/4] 11 silly lifecycle ipfs-api@12.1.0~test:node: Args: [ '-c', 'gulp test:node' ]
[11:58:50][Step 4/4] 12 silly lifecycle ipfs-api@12.1.0~test:node: Returned: code: 1  signal: null
[11:58:50][Step 4/4] 13 info lifecycle ipfs-api@12.1.0~test:node: Failed to exec test:node script
[11:58:50][Step 4/4] 14 verbose stack Error: ipfs-api@12.1.0 test:node: `gulp test:node`
[11:58:50][Step 4/4] 14 verbose stack Exit status 1
[11:58:50][Step 4/4] 14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
[11:58:50][Step 4/4] 14 verbose stack     at emitTwo (events.js:106:13)
[11:58:50][Step 4/4] 14 verbose stack     at EventEmitter.emit (events.js:191:7)
[11:58:50][Step 4/4] 14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
[11:58:50][Step 4/4] 14 verbose stack     at emitTwo (events.js:106:13)
[11:58:50][Step 4/4] 14 verbose stack     at ChildProcess.emit (events.js:191:7)
[11:58:50][Step 4/4] 14 verbose stack     at maybeClose (internal/child_process.js:877:16)
[11:58:50][Step 4/4] 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[11:58:50][Step 4/4] 15 verbose pkgid ipfs-api@12.1.0
[11:58:50][Step 4/4] 16 verbose cwd /teamcity/work/3144e2a06f62fd48/js-ipfs-api
[11:58:50][Step 4/4] 17 error Linux 4.7.1-1-ARCH
[11:58:50][Step 4/4] 18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test:node"
[11:58:50][Step 4/4] 19 error node v6.9.1
[11:58:50][Step 4/4] 20 error npm  v3.10.8
[11:58:50][Step 4/4] 21 error code ELIFECYCLE
[11:58:50][Step 4/4] 22 error ipfs-api@12.1.0 test:node: `gulp test:node`
[11:58:50][Step 4/4] 22 error Exit status 1
[11:58:50][Step 4/4] 23 error Failed at the ipfs-api@12.1.0 test:node script 'gulp test:node'.
[11:58:50][Step 4/4] 23 error Make sure you have the latest version of node.js and npm installed.
[11:58:50][Step 4/4] 23 error If you do, this is most likely a problem with the ipfs-api package,
[11:58:50][Step 4/4] 23 error not with npm itself.
[11:58:50][Step 4/4] 23 error Tell the author that this fails on your system:
[11:58:50][Step 4/4] 23 error     gulp test:node
[11:58:50][Step 4/4] 23 error You can get information on how to open an issue for this project with:
[11:58:50][Step 4/4] 23 error     npm bugs ipfs-api
[11:58:50][Step 4/4] 23 error Or if that isn't available, you can get their info via:
[11:58:50][Step 4/4] 23 error     npm owner ls ipfs-api
[11:58:50][Step 4/4] 23 error There is likely additional logging output above.
[11:58:50][Step 4/4] 24 verbose exit [ 1, true ]
```

**Comment by diasdavid** [comment]
@Kubuxu can I get an update from you on this one?

**Comment by Kubuxu** [comment]
The teamcity is for now down, when we have Jenkins running I think about running this test in a loop to check if it still crashes.

**Comment by diasdavid** [comment]
@VictorBjelkholm we need to bring this back as soon as possible. Is it possible to have it with Jenkins?

**Comment by diasdavid** [comment]
@VictorBjelkholm any updates on this one?

**Comment by diasdavid** [comment]
Ping :)

**Comment by diasdavid** [comment]
@VictorBjelkholm is this in progress with the new CI?

**Comment by diasdavid** [comment]
ANy update here?

**Comment by diasdavid** [comment]
@VictorBjelkholm any update?

**Comment by vmx** [comment]
I did a one time run locally with 0.14rc1 and a lot of tests failed. I think it's important to have the tests run before the final release.

If that's hard to do automatically on CI, I think a short term solution would be to open a PR on js-ipfs-api which always uses the most recent RC. That would at least give some indication of broken things.

**Comment by Kubuxu** [comment]
@vmx can you share the test failures. We don't want to release something that breaks js-ipfs-api.

**Comment by vmx** [comment]
@Kubuxu It's a lot of tests failing (31): https://friendpaste.com/72TbssZSoSxmdOpKxT67je

What I did to run it locally. Checkout js-ipfs-api and after an `npm install` replace the `ipfs` in `node_modules/go-ipfs-dep/go-ipfs` with the new one.

**Comment by Kubuxu** [comment]
As a reference, `master` branch builds of `go-ipfs` are available as artefacts on Jankins.

**Comment by diasdavid** [comment]
@VictorBjelkholm is tracking this also in https://github.com/ipfs/wg-qa-testing-dx/issues/15

**Comment by Kubuxu** [comment]
getting 404.

**Comment by diasdavid** [comment]
Track at https://github.com/ipfs/testing/issues/15
