### ISSUE TITLE
Node PubSub Not Working

### ISSUE THREAD

**Issue by beingmohit** [ipfs/js-ipfs-api#606]
`
TypeError: Cannot read property 'publish' of undefined
    at Function.publish.promisify (/home/mohit/projects/somethingcool/node_modules/ipfs/src/core/components/pubsub.js:54:19)
    at /home/mohit/projects/somethingcool/node_modules/promisify-es6/index.js:41:20
    at Promise (<anonymous>)
    at Object.publish (/home/mohit/projects/somethingcool/node_modules/promisify-es6/index.js:35:16)
    at IPFSPubsub.publish (/home/mohit/projects/somethingcool/node_modules/orbit-db-pubsub/src/ipfs-pubsub.js:37:25)
    at Immediate.setImmediate [as _onImmediate] (/home/mohit/projects/somethingcool/node_modules/orbit-db/src/OrbitDB.js:88:54)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5) Promise {
  <rejected> TypeError: Cannot read property 'publish' of undefined
    at Function.publish.promisify (/home/mohit/projects/somethingcool/node_modules/ipfs/src/core/components/pubsub.js:54:19)
    at /home/mohit/projects/somethingcool/node_modules/promisify-es6/index.js:41:20
    at Promise (<anonymous>)
    at Object.publish (/home/mohit/projects/somethingcool/node_modules/promisify-es6/index.js:35:16)
    at IPFSPubsub.publish (/home/mohit/projects/somethingcool/node_modules/orbit-db-pubsub/src/ipfs-pubsub.js:37:25)
    at Immediate.setImmediate [as _onImmediate] (/home/mohit/projects/somethingcool/node_modules/orbit-db/src/OrbitDB.js:88:54)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5) }
`

On digging up in ipfs code,  found 
`
this._pubsub = undefined
`
on src/core/index.js:74

Where is pubsub module code?

**Comment by beingmohit** [comment]
Sorry, wrong repo :/
