### ISSUE TITLE
hex is not a function error

### ISSUE THREAD

**Issue by bellaj** [ipfs/js-ipfs-api#612]
Hi 
I have installed the js-ipfs-api module under ubuntu without any issue But when i try in node (ipfs running) the commands below 
```
> var ipfsAPI = require('ipfs-api')
undefined
> var ipfs = ipfsAPI('/ip4/192.168.1.4/tcp/5001')// or any other alternative or ip 
```
 i get the following error : 
```
/home/user/ifps/node_modules/multicodec/src/base-table.js:8
exports['raw'] = Buffer.from('55', 'hex')
```
```
TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at Object.<anonymous> (/home/user/ifps/node_modules/multicodec/src/base-table.js:8:25)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/ifps/node_modules/multicodec/src/varint-table.js:2:19)
```
any advices?

**Comment by bellaj** [comment]
I've figured out that the node version is the source of this error. i've upgraded from v4.2.6 to V6 using 
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```
