### ISSUE TITLE
Error when adding file: "TypeError: First argument must be a string or Buffer"

### ISSUE THREAD

**Issue by leNicDev** [ipfs/js-ipfs-api#687]
When calling the add function, I'm getting the following error:

`TypeError: First argument must be a string or Buffer`

My service class (Angular/Typescript):
```typescript
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { Subscriber } from 'rxjs/Subscriber';
import { HttpClient } from '@angular/common/http';

import * as ipfsApi from 'ipfs-api';
import { AddResult } from '../models/AddResult';
import { readFileSync } from 'fs';

@Injectable()
export class IpfsService {

  ipfs: any;


  constructor(public _http: HttpClient) {
    this.ipfs = ipfsApi('localhost', '8080', { protocol: 'http' });
  }


  add(file: File, progressFunction?: Function): Observable<AddResult> {
    return new Observable<AddResult>((subscriber: Subscriber<AddResult>) => {
      const files = [
        {
          path: file.path,
          content: readFileSync(file.path)
        }
      ];

      const options = {
        progress: (bytes: number) => {
          if (progressFunction) {
            progressFunction(bytes)
          }
        }
      };

      this.ipfs.files.add(files, options, (err, res) => {
        if (err) {
          subscriber.error(err);
        } else {
          for (let i = 0; i < res.length; i++) {
            subscriber.next(res[i]);
          }
          subscriber.complete();
        }
      });
    });
  }

}
```

When checking whether `readFileSync(file.path)` returns a buffer by calling `Buffer.isBuffer(readFileSync(file.path))`, false is returned.

### Environment:
Angular: 5.2.0
Electron: 1.7.11
Node: 8.9.3 (Windows 10)

**Comment by dryajov** [comment]
Perhaps setting the explicit encoding to 'buffer' might help? Tho the docs do state (https://nodejs.org/docs/latest-v9.x/api/fs.html#fs_fs_readfilesync_path_options) that unless an encoding is specified, `Buffer` will be returned, this might be a windows oddity of some sort?

**Comment by dryajov** [comment]
Ooh... I just realized, does this run in the browser?

**Comment by leNicDev** [comment]
This is an Electron application which should technically be the same as running it on Node. I can try running it on an Ubuntu machine today.

**Comment by dryajov** [comment]
Have you tried the explicit 'buffer' encoding?

**Comment by leNicDev** [comment]
> Have you tried the explicit 'buffer' encoding?

Yes, the problem persists:
```typescript
  add(file: File, progressFunction?: Function): Observable<AddResult> {
    return new Observable<AddResult>((subscriber: Subscriber<AddResult>) => {
      const files = [
        {
          path: file.path,
          content: readFileSync(file.path)
        }
      ];

      const options = {
        progress: (bytes: number) => {
          if (progressFunction) {
            progressFunction(bytes)
          }
        },
        encoding: 'buffer'
      };

      this.ipfs.files.add(files, options, (err, res) => {
        if (err) {
          subscriber.error(err);
        } else {
          for (let i = 0; i < res.length; i++) {
            subscriber.next(res[i]);
          }
          subscriber.complete();
        }
      });
    });
  }
```

**Comment by dryajov** [comment]
I meant to add it to the `readFileSync(<path>, {encoding: 'buffer' })` (https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options), not to the `files.add` method - sorry about the confusion.

**Comment by leNicDev** [comment]
That results in the following error:
```
ERROR TypeError: Unknown encoding: buffer
    at slowToString (buffer.js:487)
    at Buffer.toString (buffer.js:500)
    at fs.readFileSync (fs.js:535)
    at fs.readFileSync (ELECTRON_ASAR.js:505)
    at Observable._subscribe (main.bundle.js:463)
    at Observable.webpackJsonp../node_modules/rxjs/Observable.js.Observable._trySubscribe (vendor.bundle.js:183574)
    at Observable.webpackJsonp../node_modules/rxjs/Observable.js.Observable.subscribe (vendor.bundle.js:183562)
    at HomeComponent.webpackJsonp../src/app/components/home/home.component.ts.HomeComponent.ipfsAddFile (main.bundle.js:275)
    at HomeComponent.webpackJsonp../src/app/components/home/home.component.ts.HomeComponent.onFileChange (main.bundle.js:265)
    at Object.eval [as handleEvent] (HomeComponent.html:13)
```

**Comment by dryajov** [comment]
Ah, interesting. Would you mind providing a quick sample project that I can take a look at?

**Comment by dryajov** [comment]
To work around the problem right now, it seems like `readFileSync` is returning a string for some reason, you can always use `Buffer.from()` on that string, and pass that to the `files.add`. I believe that this might be electron specific thing.

**Comment by leNicDev** [comment]
You can use this repo for testing: https://github.com/leNicDev/ipfs-gui
You can run the app using `npm install` and `npm start`. After choosing a file, the error occurs for me.

**Comment by dryajov** [comment]
thanks!

**Comment by leNicDev** [comment]
After trying a lot of things, I also experienced the same error in this Node.js + Koa example app: https://github.com/koajs/examples/tree/master/upload

```
TypeError: path must be a string or Buffer
      at Object.fs.open (fs.js:653:11)
      at ReadStream.open (fs.js:2057:6)
      at new ReadStream (fs.js:2044:10)
      at Object.fs.createReadStream (fs.js:1986:10)
      at F:\Projects\NodeJS\ipfs-file-sharing\src\app.js:35:23
      at dispatch (F:\Projects\NodeJS\ipfs-file-sharing\node_modules\koa-compose\index.js:42:32)
      at next (F:\Projects\NodeJS\ipfs-file-sharing\node_modules\koa-compose\index.js:43:18)
      at serve (F:\Projects\NodeJS\ipfs-file-sharing\node_modules\koa-static\index.js:53:15)
      at dispatch (F:\Projects\NodeJS\ipfs-file-sharing\node_modules\koa-compose\index.js:42:32)
      at next (F:\Projects\NodeJS\ipfs-file-sharing\node_modules\koa-compose\index.js:43:18)

```

**Comment by dryajov** [comment]
thanks @leNicDev - I'm currently investigating this issue, but I'm hesitant to say where the problem is, we have specific tests that verify this functionality which pass fine for the same version you're using.

**Comment by diasdavid** [comment]
related: #651

**Comment by diasdavid** [comment]
Now ref: https://github.com/ipfs/js-ipfs-api/pull/689

**Comment by diasdavid** [comment]
This should not be an issue in the latest version. @leNicDev please confirm.

**Comment by leNicDev** [comment]
Using ipfs-api@18.1.1, I'm still getting the same error [here](https://github.com/leNicDev/ipfs-gui/blob/master/src/app/providers/ipfs.service.ts#L53):
```typescript
add(file: File, progressFunction?: Function): Observable<AddResult> {
    return new Observable<AddResult>((subscriber: Subscriber<AddResult>) => {
      const files = [
        {
          path: file.path,
          content: readFileSync(file.path)
        }
      ];

      const options = {
        progress: (bytes: number) => {
          if (progressFunction) {
            progressFunction(bytes)
          }
        }
      };

      this.ipfs.files.add(files, options, (err, res) => {
        if (err) {
          subscriber.error(err);
        } else {
          for (let i = 0; i < res.length; i++) {
            subscriber.next(res[i]);
          }
          subscriber.complete();
        }
      });
    });
  }
```

Results in: `TypeError: First argument must be a string or Buffer`

**Comment by diasdavid** [comment]
@leNicDev print that `typeof files[0].content` to see what type it is.

**Comment by leNicDev** [comment]
`typeof files[0].content` print `object`.

**Comment by diasdavid** [comment]
This has been solved in the latest released version. Please verify. Thanks for reporting :)
