### ISSUE TITLE
DHT provide test is broken

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs-api#715]
Due to a10e3d57f0d71e934faa26ba63d371edcd86df92 the DHT provide test is broken.

You can reproduce it locally with running:

    npx aegir test -t node --files test/interface/dht.spec.js

The error is:

```
  1) .dht
       .provide
         regular:
     Error: block Qmd7qZS4T7xXtsNFdRoK1trfMs5zU94EpokQ9WFtxdPxsZ not found locally, cannot provide
      at parseError (src/utils/send-request.js:16:17)
      at ClientRequest.<anonymous> (src/utils/send-request.js:39:14)
      at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
      at Socket.socketOnData (_http_client.js:440:20)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at TCP.onread (net.js:594:20)
```

**Comment by diasdavid** [comment]
We now have all tests passing on master.
