### ISSUE TITLE
files.get works, files.stat === 'SyntaxError: Unexpected token p in JSON at position 4'

### ISSUE THREAD

**Issue by daviortega** [ipfs/js-ipfs-api#779]
Hi all,

This is my code:
```javascript
'use strict'

const fs = require('fs')

const IPFS = require('ipfs-api')
const ipfs = new IPFS(
	{
		host: 'gateway.ipfs.io',
		port: 443,
		protocol: 'https'
	})

ipfs.files.get('/ipfs/QmPeph5cHyU9TC44RUxVgPKbgEEgT9GUBKnXGwU6aLWzcj/keyimg_yc2015-09-09-98.jpg', (err, file) => {
	if (err)
		throw err
	console.log(file)
})
```
running I get:
```bash
$ node ipfsAPI.test.js
<Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 43 00 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ... >
```

switch `ipfs.files.get` to `ipfs.files.stat` leads to this:
```bash
$ node ipfsAPI.test.js
/home/ortegad/Projects/repos/etdb-bulk-download/ipfsAPI.test.js:15
                throw err
                ^

SyntaxError: Unexpected token p in JSON at position 4
    at JSON.parse (<anonymous>)
    at streamToValue (/home/ortegad/Projects/repos/etdb-bulk-download/node_modules/ipfs-api/src/utils/stream-to-json-value.js:25:18)
    at concat (/home/ortegad/Projects/repos/etdb-bulk-download/node_modules/ipfs-api/src/utils/stream-to-value.js:12:22)
    at ConcatStream.<anonymous> (/home/ortegad/Projects/repos/etdb-bulk-download/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:185:15)
    at finishMaybe (/home/ortegad/Projects/repos/etdb-bulk-download/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at afterWrite (/home/ortegad/Projects/repos/etdb-bulk-download/node_modules/readable-stream/lib/_stream_writable.js:492:3)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```
 
Any suggestions!?

**Comment by alanshaw** [comment]
This probably has something to do with the fact you're using `gateway.ipfs.io`. Does it work if you run your own daemon and point your API at it?

**Comment by alanshaw** [comment]
@daviortega yes confirmed, `gateway.ipfs.io` is read only and exposes only a limited subset of the API routes.

Details here: https://github.com/ipfs/go-ipfs/blob/9abf485d1ece2da5fbb43358893352f923410958/core/commands/root.go#L150-L183

Hope that helps!

**Comment by daviortega** [comment]
Hi @alanshaw, thank you for your response.

I understand now that the error is because `js-ipfs-api` tries to parse the `404 page not found`  (see the `p` at the position 4?).

Wouldn't be better if there was a general catch for `404` and other errors since `js-ipfs-api` is suppose to work with remote and local gateways?

**Comment by daviortega** [comment]
My next, but somewhat related question is: Why is `files/stat` not consider a read-only operation? 

I am trying to get the hash of a specific file, but I guess I will have to use `ls` for that.
