### ISSUE TITLE
failed to compile truffle react box when using ipfs-api

### ISSUE THREAD

**Issue by yshuman1** [ipfs/js-ipfs-api#863]
When trying to run `npm run build` it fails to compile and throws this error:
~~~~
yasin (master) noFilter $ npm run build

> react-box@0.1.0 build /Users/yasin/noFilter
> node scripts/build.js

Creating an optimized production build...
Failed to compile.

static/js/main.7a3ef080.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/ipfs-api/src/utils/module-config.js:7,0]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-box@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-box@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yasin/.npm/_logs/2018-09-26T21_32_05_200Z-debug.log
~~~~

This is what the debug log shows:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle react-box@0.1.0~prebuild: react-box@0.1.0
6 info lifecycle react-box@0.1.0~build: react-box@0.1.0
7 verbose lifecycle react-box@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle react-box@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/yasin/noFilter/node_modules/.bin:/Users/yasin/.cargo/bin:/Users/yasin/google-cloud-sdk/bin:/usr/local/opt/python@2/libexec/bin:/Users/yasin/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin:/Users/yasin/go/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/mysql/bin/
9 verbose lifecycle react-box@0.1.0~build: CWD: /Users/yasin/noFilter
10 silly lifecycle react-box@0.1.0~build: Args: [ '-c', 'node scripts/build.js' ]
11 silly lifecycle react-box@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle react-box@0.1.0~build: Failed to exec build script
13 verbose stack Error: react-box@0.1.0 build: `node scripts/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid react-box@0.1.0
15 verbose cwd /Users/yasin/noFilter
16 verbose Darwin 18.0.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error react-box@0.1.0 build: `node scripts/build.js`
22 error Exit status 1
23 error Failed at the react-box@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
~~~~

Any advice on how to fix this would be appreciated.

**Comment by yshuman1** [comment]
What I found is that uglify.js is not playing nice with js-ipfs. I commented it out in the config/webpack.config.prod.js file and it was successful
