### ISSUE TITLE
res.req.getHeaders is not a function in nodejs

### ISSUE THREAD

**Issue by madelacruzs** [ipfs/js-ipfs-api#867]
TypeError: res.req.getHeaders is not a function
    at ClientRequest.<anonymous> (/Users/madelacruzs/node-js-projects/Github/IPFS-GetSet/node_modules/ipfs-api/src/utils/send-request.js:41:38)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)

Happens when I call:
ipfs.files.add(files, (err, result) => { 
    });  

**Posible solution**: /src/utils/send-request.js:41:38)

**I changed the next line**

  log(res.req.method, `${res.req.getHeaders().host}${res.req.path}`, res.statusCode, res.statusMessage)
     
**For this line**
log(res.req.method, `${res.req._headers.host}${res.req.path}`, res.statusCode, res.statusMessage)

**Comment by alanshaw** [comment]
what version of Node.js are you using?

**Comment by madelacruzs** [comment]
I'm using v6.11.1

**Comment by alanshaw** [comment]
@madelacruzs please upgrade to the latest LTS 8.x and this should start working.

**Comment by madelacruzs** [comment]
Thanks !!!
